[package]
name = "steve"
version = "0.1.0"
edition = "2021"
autobins = false

[[bin]]
name = "steve"
path = "src/bin/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.26", features = ["serde"] }
clap = { version = "4.3.4", features = ["derive"] }
dialoguer = "0.10.4"
futures-util = "0.3.28"
indicatif = "0.17.5"
lenient_semver = { version = "0.4.2", features = ["semver"] }
notify = "6.0.1"
oauth2 = "4.4.1"
reqwest = { version = "0.11.18", features = ["json", "stream"] }
semver = "1.0.18"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.97"
shellexpand = "3.1.0"
tokio = { version = "1.28.2", features = ["macros"] }
url = { version = "2.4.0", features = ["serde"] }
zip-extract = "0.1.2"
