[package]
name = "mcli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.26", features = ["serde"] }
clap = { version = "4.3.4", features = ["derive"] }
envsubst = "0.2.1"
futures-util = "0.3.28"
indicatif = "0.17.5"
oauth2 = "4.4.1"
reqwest = { version = "0.11.18", features = ["json", "stream"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.97"
tokio = { version = "1.28.2", features = ["macros"] }
zip-extract = "0.1.2"
