[package]
name = "mcli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.4", features = ["derive"] }
envsubst = "0.2.1"
futures-util = "0.3.28"
indicatif = "0.17.5"
reqwest = { version = "0.11.18", features = ["json", "stream"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.97"
sha-1 = "0.10.1"
tokio = { version = "1.28.2", features = ["macros"] }
